stages:
  - prepare_image
  - validate
  - build
  - prod
  - prepare
  - deploy
  - cleanup

# 1. Include Catalog Components
include:
  - component: $CI_SERVER_FQDN/vedat/gitlab-ci-templates/sync-to-wikijs@~latest
    inputs:
      page_path: "technical/project/botuk_zigbee"
      page_title: "botuk_zigbee"
      filename: "README.md"
  - component: $CI_SERVER_FQDN/vedat/gitlab-ci-templates/check_version@v1.5.5
    inputs:
      versionfile: "settings.conf"
      versionkey: "FIRMWARE_VERSION"
  - component: $CI_SERVER_FQDN/vedat/gitlab-ci-templates/restrict_pr_to_main@~latest
  - component: $CI_SERVER_FQDN/vedat/gitlab-ci-templates/check_parameter@~latest
    inputs:
      check_file: "settings.conf"
      check_key: "TESTING"
      expected_value: "0"

# 2. Include Local Sub-Pipelines
  - local: '.github/workflows/templates.yml'
  - local: '.github/workflows/validate.yml'
  - local: '.github/workflows/build.yml'
  - local: '.github/workflows/deploy.yml'
  - local: '.github/workflows/cleanup.yml'

# 3. Component Extends
sync_wiki:
  extends: .sync_to_wikijs
check_version:
  extends: .check_version
restrict_pr_to_main:
  extends: .restrict_pr_to_main
check_parameter:
  extends: .check_parameter