name: Build ESP32-H2 Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IDF_TOOLS_PATH: ${{ github.workspace }}/tools

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up ESP-IDF toolchain
      - name: Set up ESP-IDF
        run: |
          sudo apt-get install -y git wget flex bison gperf python3 python3-pip python3-venv cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0
          mkdir -p ~/esp
          cd ~/esp
          git clone -b v5.2.3 --recursive https://github.com/espressif/esp-idf.git
          cd ~/esp/esp-idf
          ./install.sh esp32h2

      # Install zigpy
      - name: Install zigpy
        run: |
          . $HOME/esp/esp-idf/export.sh
          pip3 install zigpy

      # Build the project for ESP32-H2
      - name: Build Project
        run: |
          . $HOME/esp/esp-idf/export.sh
          idf.py set-target esp32h2  # Set target for ESP32-H2
          idf.py build