name: Block merge if todos are incomplete in PR description
on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check_pr_description:
    runs-on: ubuntu-latest
    steps:
      - name: Check for unchecked to-do items in PR comments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          comments=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "${{ github.event.pull_request.comments_url }}" | jq -r '.[].body')
          
          if echo "$comments" | grep '- \[ \]'; then
            echo "Error: Found incomplete to-do items in PR comments."
            exit 1
          else
            echo "No incomplete to-do items found in PR comments."
          fi
