name: Block merge if todos are incomplete
on: pull_request

jobs:
  check_todos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for unchecked todos
        run: |
          if grep -rn '\- \[ \]' .; then
            echo "Found incomplete to-do items"
            exit 1
          else
            echo "All to-do items are complete"
          fi
