name: Check Firmware Version Change

on:
  pull_request:
    branches:
      - main

jobs:
  check-version-change:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is fetched for comparison

      - name: Get FIRMWARE_VERSION and VERSION from main
        id: main_values
        run: |
          # Fetch main branch for comparison
          git fetch origin main:main
          # Extract values from main branch
          MAIN_FIRMWARE_VERSION=$(git show main:settings.conf | grep "^FIRMWARE_VERSION=" | cut -d '=' -f 2)
          MAIN_VERSION=$(git show main:settings.conf | grep "^VERSION=" | cut -d '=' -f 2)
          echo "main_firmware_version=$MAIN_FIRMWARE_VERSION" >> $GITHUB_ENV
          echo "main_version=$MAIN_VERSION" >> $GITHUB_ENV

      - name: Get FIRMWARE_VERSION and VERSION from develop
        id: develop_values
        run: |
          # Extract values from develop branch (current branch)
          DEVELOP_FIRMWARE_VERSION=$(grep "^FIRMWARE_VERSION=" settings.conf | cut -d '=' -f 2)
          DEVELOP_VERSION=$(grep "^VERSION=" settings.conf | cut -d '=' -f 2)
          echo "develop_firmware_version=$DEVELOP_FIRMWARE_VERSION" >> $GITHUB_ENV
          echo "develop_version=$DEVELOP_VERSION" >> $GITHUB_ENV

      - name: Check if versions have changed
        run: |
          # Compare versions from develop and main
          if [[ "$main_firmware_version" == "$develop_firmware_version" ]] && [[ "$main_version" == "$develop_version" ]]; then
            echo "Error: FIRMWARE_VERSION and VERSION have not changed."
            exit 1
          else
            echo "Success: FIRMWARE_VERSION or VERSION has changed."
          fi
