name: Block merge if todos are incomplete in PR comments

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  issue_comment:
    types: [created, edited]

jobs:
  check_pr_comments:
    runs-on: ubuntu-latest

    steps:
      - name: Check for unchecked to-do items in PR comments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number || github.event.issue.number }}
          REPO: ${{ github.repository }}
        run: |
          # Fetch all comments in the pull request
          comments=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments" | jq -r '.[].body')

          # Check each comment for unchecked to-do items
          if echo "$comments" | grep '- \[ \]'; then
            echo "Error: Found incomplete to-do items in PR comments."
            exit 1
          else
            echo "All to-do items are complete in PR comments."
          fi
