name: Update Release Note on PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  update-release-note:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures all branches are available

      - name: Set Git configuration
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create or Update RELEASE_NOTE.md
        run: |
          echo "Updating RELEASE_NOTE.md with latest merge information"
          # Append information to RELEASE_NOTE.md (example)
          echo "- Merged PR #${{ github.event.pull_request.number }} by ${{ github.event.pull_request.user.login }}" >> RELEASE_NOTE.md
          git add RELEASE_NOTE.md
          git commit -m "Update RELEASE_NOTE.md with latest merge information" || echo "No changes to commit"

      - name: Push Changes to Main
        run: |
          # Ensure we are pushing to the correct branch
          git fetch origin main
          git checkout main
          git rebase develop
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
