name: Enforce PR Template

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/PULL_REQUEST_TEMPLATE.md' # Optional: Only run if the PR affects this file

jobs:
  check-template:
    runs-on: ubuntu-latest
    if: github.base_ref == 'main' && github.head_ref == 'dev' # Trigger only if PR is from dev to main

    steps:
      - name: Check Pull Request Template
        id: check_pr_body
        run: |
          if ! grep -q "## Description" "$GITHUB_EVENT_PATH"; then
            echo "::error::Pull request template is missing the 'Description' section. Please use the template provided."
            exit 1
          fi
        shell: bash
