name: Enforce PR Template

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  check-template:
    runs-on: ubuntu-latest
    if: github.base_ref == 'main' && github.head_ref == 'dev'

    steps:
      - name: Check Pull Request Template
        run: |
          # Extract the PR body from the event JSON
          PR_BODY=$(jq -r .pull_request.body "$GITHUB_EVENT_PATH")
          
          # Check if the required '## Description' section is in the PR body
          if [[ -z "$PR_BODY" || "$PR_BODY" != *"## Description"* ]]; then
            echo "::error::Pull request template is missing the 'Description' section. Please use the template provided."
            exit 1
          fi
        shell: bash
