name-template: 'Release $NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 New Features'
    labels:
      - feature
  - title: '🐛 Bug Fixes'
    labels:
      - bug
  - title: '🧹 Maintenance'
    labels:
      - maintenance
  - title: '🗂️ Closed Issues'
    labels:
      - closed-issue  # Label issues with `closed-issue` to include in release notes

change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
template: |
  ## What's Changed
  $CHANGES

  ## Closed Issues
  $ISSUES
